---
# DB
- name: Configure db host and start mongodb
  tags: db-tag
  become: true # <-- Выполнить задание от root
  # Применять сценарий мы хотим только к серверам группы db или ко всем?
  hosts: db
  vars:
    mongo_bind_ip: 0.0.0.0 # <-- Переменная задается в блоке vars

  tasks:
    - name: Change mongo config file
      template:
        src: templates/mongod.conf.j2 # <-- Путь до локального файла-шаблона
        dest: /etc/mongod.conf # <-- Путь на удаленном хосте
        mode: 0644 # <-- Права на файл, которые нужно установить
      notify: restart mongod

  handlers: # <-- Добавим блок handlers и задачу
    - name: restart mongod
      service: name=mongod state=restarted

# App
- name: Configure app and run
  tags: app-tag
  become: true # <-- Выполнить задание от root
  hosts: app
  vars:
    db_host: 10.156.15.199  # <-- DB Host local/public ip

  tasks:
    - name: Add unit file for Puma
      copy:
        src: files/puma.service
        dest: /etc/systemd/system/puma.service
      notify: reload puma

    - name: enable puma
      systemd: name=puma enabled=yes

    - name: Add config for DB connection
      template:
          src: templates/db_config.j2
          dest: /home/appuser/db_config
          owner: appuser
          group: appuser

  handlers:
    - name: reload puma
      systemd: name=puma state=restarted

# Deploy
- name: Deploy app
  tags: deploy-tag
  hosts: app

  tasks:
    - name: Fetch the latest version of application code
      git:
        repo: 'https://github.com/express42/reddit.git'
        dest: /home/appuser/reddit
        version: monolith # <-- Указываем нужную ветку
      notify: reload puma

    - name: Bundle install
      bundler:
        state: present
        chdir: /home/appuser/reddit # <-- В какой директории выполнить команду bundle

  handlers:
    - name: reload puma
      become: true # <-- Выполнить задание от root
      systemd: name=puma state=restarted
